name: Build (no publish)
on:
  workflow_dispatch: {}
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with: { node-version: '20' }
    - uses: actions/setup-python@v5
      with: { python-version: '3.12' }
    - name: Install Node deps
      working-directory: voice-assistant-apps/desktop
      run: npm ci
    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Prepare backend binary (skip – manual step)
      run: echo "Build backend binaries manually and commit them or upload as artifacts. This workflow intentionally does not build."
    - name: Electron build (dry)
      working-directory: voice-assistant-apps/desktop
      run: echo "Run 'npm run dist:linux' or 'npm run dist:win' locally when ready."
